name: Native Build

on:
  workflow_dispatch:
#on:
#  release:
#    types: [created]

jobs:
  build-native:
    name: Build native on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    env:
      QUARKUS_NATIVE_CONTAINER_BUILD: "false"
    steps:
      - uses: actions/checkout@v5
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: 21
          distribution: graalvm-community
          github-token: ${{ secrets.GITHUB_TOKEN }}
          cache: maven
      - run: |
          echo "Runner OS: $RUNNER_OS"
          echo "JAVA_HOME: $JAVA_HOME"
          java -version
          gu --version
        shell: bash
      - run: |
          if [ "$RUNNER_OS" = "Windows" ]; then
            ./mvnw.cmd --show-version --batch-mode --no-transfer-progress install -DskipTests -P op,prod,native -Dquarkus.native.container-build=${QUARKUS_NATIVE_CONTAINER_BUILD}
          else
            ./mvnw --show-version --batch-mode --no-transfer-progress install -DskipTests -P op,prod,native -Dquarkus.native.container-build=${QUARKUS_NATIVE_CONTAINER_BUILD}
          fi
        shell: bash
      - name: Upload native artifacts
        uses: actions/upload-artifact@v4
        with:
          name: hal-op-standalone-native-${{ runner.os }}
          path: |
            op/standalone/target/**
          if-no-files-found: warn
